services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    env_file: ./backend/.env
    hostname: backend
    restart: unless-stopped
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    hostname: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - backend
