services:
  ollama:
    image: ollama/ollama
    hostname: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ~/.ollama:/root/.ollama
  # docker compose exec ollama ollama run gemma3:4b

  backend:
    build:
      context: ./adopt-a-seed-api
      dockerfile: Dockerfile
    image: adopt-a-seed-api
    env_file: ./adopt-a-seed-api/.env
    hostname: backend
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - ollama

  frontend:
    build:
      context: ./adopt-a-seed
      dockerfile: Dockerfile
    image: adopt-a-seed
    hostname: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - backend
